service: gov-info-COVID-19

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
       # TODO: 権限は要確認
      Action:
        - "lambda:*"
        - "dynamodb:*"
      Resource: "*"

functions:
  cal-regist:
    handler: handler.main
    events:
      - schedule:
        rate: cron(*/5 * * * ? *)
        enabled: false
