service: gov-info-COVID-19

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: ap-northeast-1

custom:
  defaultStage: prod
  profiles:
    prod: sls
  otherfile:
    environment:
      prod: ${file(env.yml)}

functions:
  RT_bot:
    handler: handler.main
    events:
      - schedule: cron(*/20 * * * ? *)
    environment:
      CONSUMER_KEY: ${self:custom.otherfile.environment.${self:provider.stage}.CONSUMER_KEY}
      CONSUMER_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.CONSUMER_SECRET}
      ACCESS_TOKEN: ${self:custom.otherfile.environment.${self:provider.stage}.ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.ACCESS_TOKEN_SECRET}